import { describe, expect, test } from "bun:test";
import { sheetScreenshotTargets } from "./capture-screenshots";

describe("sheet screenshot targets", () => {
  test("captures sheet, group-use, wiki, and edited states", () => {
    expect(sheetScreenshotTargets.every((target) => !("capture" in target))).toBe(true);
    expect(sheetScreenshotTargets).toEqual([
      {
        fileName: "home-public-light.png",
        label: "Public home light",
        path: "/",
        role: "public",
        theme: "light",
      },
      {
        fileName: "home-public-dark.png",
        label: "Public home dark",
        path: "/",
        role: "public",
        theme: "dark",
      },
      {
        action: "open-menu",
        fileName: "home-admin-player-menu-light.png",
        label: "Combined admin player menu light",
        path: "/",
        role: "admin_player",
        theme: "light",
      },
      {
        action: "open-menu",
        fileName: "home-admin-player-menu-dark.png",
        label: "Combined admin player menu dark",
        path: "/",
        role: "admin_player",
        theme: "dark",
      },
      {
        action: "scroll-local-list",
        fileName: "local-characters-light.png",
        label: "Local characters light",
        path: "/local/characters",
        prepare: "local-play",
        role: "public",
        theme: "light",
      },
      {
        action: "scroll-local-list",
        fileName: "local-campaigns-dark.png",
        label: "Local campaigns dark",
        path: "/local/campaigns",
        prepare: "local-play",
        role: "public",
        theme: "dark",
      },
      {
        fileName: "lynott-sheet-light.png",
        label: "Lynott sheet light",
        path: "/sheet/lynott",
        role: "player",
        theme: "light",
      },
      {
        fileName: "lynott-sheet-dark.png",
        label: "Lynott sheet dark",
        path: "/sheet/lynott",
        role: "player",
        theme: "dark",
      },
      {
        action: "edit-strength",
        fileName: "lynott-ability-edit-light.png",
        label: "Lynott ability edit light",
        path: "/sheet/lynott",
        role: "player",
        theme: "light",
      },
      {
        action: "edit-strength",
        fileName: "lynott-ability-edit-dark.png",
        label: "Lynott ability edit dark",
        path: "/sheet/lynott",
        role: "player",
        theme: "dark",
      },
      {
        action: "edit-breastplate",
        fileName: "lynott-core-card-edit-light.png",
        label: "Lynott core card edit light",
        path: "/sheet/lynott",
        role: "player",
        theme: "light",
      },
      {
        action: "edit-breastplate",
        fileName: "lynott-core-card-edit-dark.png",
        label: "Lynott core card edit dark",
        path: "/sheet/lynott",
        role: "player",
        theme: "dark",
      },
      {
        fileName: "lynott-skills-light.png",
        label: "Lynott skills light",
        path: "/sheet/lynott",
        role: "player",
        tabId: "skills",
        theme: "light",
      },
      {
        fileName: "lynott-skills-dark.png",
        label: "Lynott skills dark",
        path: "/sheet/lynott",
        role: "player",
        tabId: "skills",
        theme: "dark",
      },
      {
        action: "open-first-accordion",
        fileName: "lynott-spellcasting-rule-text-light.png",
        label: "Lynott spellcasting rule text light",
        path: "/sheet/lynott",
        role: "player",
        tabId: "spellcasting",
        theme: "light",
      },
      {
        action: "open-first-accordion",
        fileName: "lynott-spellcasting-rule-text-dark.png",
        label: "Lynott spellcasting rule text dark",
        path: "/sheet/lynott",
        role: "player",
        tabId: "spellcasting",
        theme: "dark",
      },
      {
        action: "open-first-accordion",
        fileName: "lynott-actions-rule-text-light.png",
        label: "Lynott actions rule text light",
        path: "/sheet/lynott",
        role: "player",
        tabId: "actions",
        theme: "light",
      },
      {
        action: "open-first-accordion",
        fileName: "lynott-actions-rule-text-dark.png",
        label: "Lynott actions rule text dark",
        path: "/sheet/lynott",
        role: "player",
        tabId: "actions",
        theme: "dark",
      },
      {
        action: "edit-stealth",
        fileName: "lynott-skills-edit-light.png",
        label: "Lynott skills edit light",
        path: "/sheet/lynott",
        role: "player",
        tabId: "skills",
        theme: "light",
      },
      {
        action: "edit-stealth",
        fileName: "lynott-skills-edit-dark.png",
        label: "Lynott skills edit dark",
        path: "/sheet/lynott",
        role: "player",
        tabId: "skills",
        theme: "dark",
      },
      {
        action: "roll-stealth",
        fileName: "lynott-skills-roll-light.png",
        label: "Lynott skills roll light",
        path: "/sheet/lynott",
        role: "player",
        tabId: "skills",
        theme: "light",
      },
      {
        action: "roll-stealth",
        fileName: "lynott-skills-roll-dark.png",
        label: "Lynott skills roll dark",
        path: "/sheet/lynott",
        role: "player",
        tabId: "skills",
        theme: "dark",
      },
      {
        fileName: "lynott-background-faction.png",
        label: "Lynott background faction",
        path: "/sheet/lynott",
        role: "player",
        tabId: "background",
        theme: "light",
      },
      {
        action: "open-bless-accordion",
        fileName: "mira-spellcasting-light.png",
        label: "Mira spellcasting light",
        path: "/sheet/mira-voss",
        role: "mira_player",
        tabId: "spellcasting",
        theme: "light",
      },
      {
        action: "open-bless-accordion",
        fileName: "mira-spellcasting-dark.png",
        label: "Mira spellcasting dark",
        path: "/sheet/mira-voss",
        role: "mira_player",
        tabId: "spellcasting",
        theme: "dark",
      },
      {
        action: "scroll-roster-table",
        fileName: "player-roster.png",
        label: "Player roster",
        path: "/characters",
        role: "player",
        theme: "light",
      },
      {
        action: "scroll-roster-table",
        fileName: "player-roster-dark.png",
        label: "Player roster dark",
        path: "/characters",
        role: "player",
        theme: "dark",
      },
      {
        action: "scroll-admin-users",
        fileName: "admin-tables-light.png",
        label: "Admin tables light",
        path: "/admin",
        role: "admin",
        theme: "light",
      },
      {
        action: "scroll-admin-users",
        fileName: "admin-tables-dark.png",
        label: "Admin tables dark",
        path: "/admin",
        role: "admin",
        theme: "dark",
      },
      {
        fileName: "admin-invite-handoff-light.png",
        label: "Admin invite handoff light",
        path: "/admin?handoff=invite&url=%2Finvites%2Fscreenshot-token&email=screenshot.player%40example.local&role=player&expires=2026-05-28T12%3A00%3A00.000Z",
        role: "admin",
        theme: "light",
      },
      {
        fileName: "admin-invite-handoff-dark.png",
        label: "Admin invite handoff dark",
        path: "/admin?handoff=invite&url=%2Finvites%2Fscreenshot-token&email=screenshot.player%40example.local&role=player&expires=2026-05-28T12%3A00%3A00.000Z",
        role: "admin",
        theme: "dark",
      },
      {
        fileName: "gm-campaign-light.png",
        label: "Game Master campaign light",
        path: "/campaigns/rovnost-shadows",
        role: "game_master",
        theme: "light",
      },
      {
        fileName: "gm-campaign-dark.png",
        label: "Game Master campaign dark",
        path: "/campaigns/rovnost-shadows",
        role: "game_master",
        theme: "dark",
      },
      {
        fileName: "gm-prep-workspace-light.png",
        label: "Game Master prep workspace light",
        path: "/campaigns/rovnost-shadows/prep",
        role: "game_master",
        theme: "light",
      },
      {
        fileName: "gm-prep-workspace-dark.png",
        label: "Game Master prep workspace dark",
        path: "/campaigns/rovnost-shadows/prep",
        role: "game_master",
        theme: "dark",
      },
      {
        fileName: "gm-player-preview-light.png",
        label: "Game Master player preview light",
        path: "/campaigns/rovnost-shadows/preview/player",
        role: "game_master",
        theme: "light",
      },
      {
        fileName: "gm-player-preview-dark.png",
        label: "Game Master player preview dark",
        path: "/campaigns/rovnost-shadows/preview/player",
        role: "game_master",
        theme: "dark",
      },
      {
        fileName: "gm-npc-list-light.png",
        label: "Game Master NPC list light",
        path: "/campaigns/rovnost-shadows/npcs",
        role: "game_master",
        theme: "light",
      },
      {
        fileName: "gm-npc-list-dark.png",
        label: "Game Master NPC list dark",
        path: "/campaigns/rovnost-shadows/npcs",
        role: "game_master",
        theme: "dark",
      },
      {
        fileName: "player-npc-list-light.png",
        label: "Player NPC list light",
        path: "/campaigns/rovnost-shadows/npcs",
        role: "player",
        theme: "light",
      },
      {
        fileName: "player-npc-list-dark.png",
        label: "Player NPC list dark",
        path: "/campaigns/rovnost-shadows/npcs",
        role: "player",
        theme: "dark",
      },
      {
        fileName: "gm-npc-detail-light.png",
        label: "Game Master NPC detail light",
        path: "/campaigns/rovnost-shadows/npcs/magister-vallen",
        role: "game_master",
        theme: "light",
      },
      {
        fileName: "gm-npc-detail-dark.png",
        label: "Game Master NPC detail dark",
        path: "/campaigns/rovnost-shadows/npcs/magister-vallen",
        role: "game_master",
        theme: "dark",
      },
      {
        fileName: "gm-image-library-light.png",
        label: "Game Master image library light",
        path: "/campaigns/rovnost-shadows/images",
        role: "game_master",
        theme: "light",
      },
      {
        fileName: "gm-image-library-dark.png",
        label: "Game Master image library dark",
        path: "/campaigns/rovnost-shadows/images",
        role: "game_master",
        theme: "dark",
      },
      {
        fileName: "gm-image-detail-light.png",
        label: "Game Master image detail light",
        path: "/campaigns/rovnost-shadows/images/asset_magister_vallen",
        role: "game_master",
        theme: "light",
      },
      {
        fileName: "gm-image-detail-dark.png",
        label: "Game Master image detail dark",
        path: "/campaigns/rovnost-shadows/images/asset_magister_vallen",
        role: "game_master",
        theme: "dark",
      },
      {
        fileName: "gm-imports-light.png",
        label: "Game Master imports light",
        path: "/campaigns/rovnost-shadows/imports",
        role: "game_master",
        theme: "light",
      },
      {
        fileName: "gm-imports-dark.png",
        label: "Game Master imports dark",
        path: "/campaigns/rovnost-shadows/imports",
        role: "game_master",
        theme: "dark",
      },
      {
        action: "scroll-campaign-assets",
        fileName: "gm-campaign-assets-light.png",
        label: "Game Master campaign assets light",
        path: "/campaigns/rovnost-shadows",
        role: "game_master",
        theme: "light",
      },
      {
        action: "scroll-campaign-assets",
        fileName: "gm-campaign-assets-dark.png",
        label: "Game Master campaign assets dark",
        path: "/campaigns/rovnost-shadows",
        role: "game_master",
        theme: "dark",
      },
      {
        action: "scroll-campaign-rules-sources",
        fileName: "gm-campaign-rules-sources-light.png",
        label: "Game Master campaign rules sources light",
        path: "/campaigns/rovnost-shadows",
        role: "game_master",
        theme: "light",
      },
      {
        action: "scroll-campaign-rules-sources",
        fileName: "gm-campaign-rules-sources-dark.png",
        label: "Game Master campaign rules sources dark",
        path: "/campaigns/rovnost-shadows",
        role: "game_master",
        theme: "dark",
      },
      {
        fileName: "wiki-factions-image.png",
        label: "Wiki page with image",
        path: "/campaigns/rovnost-shadows/wiki/factions-guide",
        role: "player",
        theme: "light",
      },
      {
        action: "scroll-rules-results",
        fileName: "rules-spells.png",
        label: "Public rules spell list",
        path: "/rules?type=spell&level=1",
        role: "public",
        theme: "light",
      },
      {
        action: "scroll-rule-detail",
        fileName: "rules-bless.png",
        label: "Public Rules Bless detail",
        path: "/rules/spell/bless",
        role: "public",
        theme: "light",
      },
      {
        fileName: "lynott-edited-sheet.png",
        label: "Lynott edited sheet light",
        path: "/sheet/lynott",
        prepare: "edited-sheet",
        role: "player",
        theme: "light",
      },
      {
        fileName: "lynott-edited-sheet-dark.png",
        label: "Lynott edited sheet dark",
        path: "/sheet/lynott",
        prepare: "edited-sheet",
        role: "player",
        theme: "dark",
      },
    ]);
  });
});
